version: '3.8'
#Nem precisa de secretos, só precisa criar o arquivo .env com as variáveis de ambiente ou chumbar ai mesmo ksskks
services:
  app:
    build: .
    environment:
      PORT: 3000
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    command: npm run dev
  financas-db-web:
    restart: alwaays
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: ${PMA_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '5001:80'

volumes:
  data:

#Rodando comando:
#docker-compose up -d
#sudo kill -9 $(sudo lsof -t -i:3051) -> Derruba a porta caso o container ocupe ela
#sudo docker rm 4edeb0ba295a -> ID do container que deseja derrubar caso de duplicação ou erro de url