apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi



# Esse arquivo serve para criar um PersistentVolumeClaim para o MySQL no Kubernetes, para que o banco de dados possa armazenar dados de forma persistente.