apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-finance-api
spec:
  selector:
    matchLabels:
      app: personal-finance-api
  template:
    metadata:
      labels:
        app: personal-finance-api
    spec:
      containers:
        - name: personal-finance-api
          image: ghcr.io/thalyssonEmanoel/personal-finance-management:latest
          ports:
            - containerPort: 3100
          resources:
            limits:
              memory: 512Mi #Coloquei, pois é uma boa prática
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: api-secrets
          env:
            - name: DATABASE_URL
              value: mysql://$(MYSQL_USER):$(MYSQL_PASSWORD)@mysql:3306/$(MYSQL_DATABASE)
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: database
---
apiVersion: v1
kind: Service
metadata:
  name: personal-finance-api
spec:
  type: NodePort
  ports:
    - port: 3100
      nodePort: 30002
  selector:
    app: personal-finance-api
