name: Deploy to Kubernetes

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .
          docker push ghcr.io/${{ github.repository }}:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Apply Kubernetes manifests
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml
          kubectl apply -f configmap/mysql-secrets.yaml
          kubectl apply -f configmap/api-secrets.yaml
          kubectl apply -f configmap/api-configmap.yaml
          kubectl apply -f deploy/mysql-pvc.yaml
          kubectl apply -f deploy/mysql-deployment.yaml
          kubectl apply -f deploy/phpmyadmin.yaml
          kubectl apply -f deploy/personal-finance-api.yaml
